spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sarafan?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kzm_vlad
    password: 123root@
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
#  session:
#    jdbc:
#      initialize-schema: always
#      table-name: SPRING_SESSION
#      schema: classpath:session_tables.sql

security:
  oauth2:
    client:
      client-id: 497830438-iph35pn7c0bchd0k286q7e9isgsp011i.apps.googleusercontent.com
      client-secret: ${clientSecret}
      client-authentication-scheme: form
      scope: openid,email,profile
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true

server:
  port: 8080

